const questions = [
  {
    question: "What is React?",
    options: [
      "Database",
      "JavaScript Library",
      "Programming Language",
      "Server"
    ],
    answer: "JavaScript Library"
  },
  {
    question: "Who developed React?",
    options: [
      "Google",
      "Facebook",
      "Microsoft",
      "Amazon"
    ],
    answer: "Facebook"
  },
  {
    question: "Which hook is used for state management?",
    options: [
      "useFetch",
      "useState",
      "useEffect",
      "useRouter"
    ],
    answer: "useState"
  }
];

export default questions;
